### ISSUE TITLE
ERROR : File does not exist

### ISSUE THREAD

**Issue by wenjiexiaomeng** [daisieh/plann#7]
Hi,

I am try to annotate a gingko chloroplast genome, but there seems to be a error and I couldn't figure this out.
Below is my command line , could you give me a hand?

Best, 
Wenjie
##############################################################################
perl plann-1.1/plann.pl -reference gingko.gb -fastafile Option_1_TM130A_chloro.fasta -sample gingko.gb
##############################################################################
Comparing reference genbank gingko.gb to new plastome Option_1_TM130A_chloro.fasta
File does not exist:  at plann-1.1/lib/Blast.pm line 191.

**Comment by daisieh** [comment]
Usually when people get that error, it's because blast is not installed on their machine. Can you verify that blastn is executable from your command line?

**Comment by wenjiexiaomeng** [comment]
Hi,
I have installed blast on the cluster and I also can use bl2seq in command line, But it still has this problem..

**Comment by daisieh** [comment]
What happens if you run blastn on your cluster? (run `blastn` from the command line)
